# OneDark Deep – Kitty

background            #1a212e
foreground            #93a4c3
selection_background  #41a7fc
selection_foreground  #1a212e
cursor                #93a4c3
cursor_text_color     #1a212e

# Normal colors
color0  #0c0e15
color1  #f65866
color2  #8bcd5b
color3  #efbd5d
color4  #41a7fc
color5  #c75ae8
color6  #34bfd0
color7  #93a4c3

# Bright colors
color8  #455574
color9  #f65866
color10 #8bcd5b
color11 #f2cc81
color12 #54b0fd
color13 #c75ae8
color14 #34bfd0
color15 #ffffff

